//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************

(function () {
    angular
	.module('app')
	.factory('databaseFactory', ['$http', function($http) {

    var urlBase = '/api/database';
    var databaseFactory = {};

		
		databaseFactory.put = function (request) {
        var operation= $http({method: 'PUT', url: urlBase, params: request });
		return operation.then(function(data, status, headers, config) {
            return data.data;
        }, function(error) {
		//TODO: find the injectable logger and use it
		    console.log(error);
            return  { isOk: false, message: error };
        });
		
    };

		

	return databaseFactory;
}]);
}())
